//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BinhLuan
    {
        [Display(Name = "Mã bình luận")]
        public int MaBL { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public string MaSP { get; set; }
        [Display(Name = "Mã Khách Hàng")]
        public string MaKH { get; set; }
        [Display(Name = "Nội Dung Bình Luận")]
        public string NoiDung { get; set; }
        [Display(Name = "Ngày Đăng")]
        public Nullable<System.DateTime> NgayDang { get; set; }
        [Display(Name = "Họ Tên")]
        public string HoTen { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "Đã trả lời")]
        public string DaTraLoi { get; set; }
        public Nullable<int> Parent { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
