//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ChiTietDonHang
    {
        [Display(Name = "Mã đơn hàng")]
        public string MaDH { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public string MaSP { get; set; }
        [Display(Name = "Số Lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual DonHangKH DonHangKH { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
