//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DanhsachdangkisanphamNCC
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        [Display(Name = "Mã Sản phẩm cần mua")]
        public Nullable<int> MaSPCanMua { get; set; }
        [Display(Name = "Mã nhà cung cấp")]
        public string MaNCC { get; set; }
        [Display(Name = "Ghi chú")]
        public string Ghichu { get; set; }
        [Display(Name = "Ngày đăng kí")]
        public Nullable<System.DateTime> NgayDK { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<int> Trangthai { get; set; }
        [Display(Name = "Đơn giá")]
        public Nullable<int> TienmoiSP { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual Sanphamcanmua Sanphamcanmua { get; set; }
    }
}
