//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oauth
    {
        public string ID { get; set; }
        public string Consumer_key { get; set; }
        public string Callback { get; set; }
        public string Request_token { get; set; }
        public string Verifier_token { get; set; }
        public Nullable<System.DateTime> Date_comsumer { get; set; }
        public string MaNCC { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpiresTime { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
